- name: Debian upgrade first
  hosts: vps
  become: true
  gather_facts: true
  roles:
    - role: debian_upgrade
      tags: [debian_upgrade]

- name: Common hardening after upgrade
  hosts: vps
  become: true
  gather_facts: true
  roles:
    - role: common
      tags: [common]

- name: Docker CE installation
  hosts: vps
  become: true
  gather_facts: true
  roles:
    - role: docker_ce
      tags: [docker_ce]

- name: Deploy iot-common compose stack
  hosts: vps
  become: true
  gather_facts: true
  roles:
    - role: iot_common_deploy
      tags: [iot_common_deploy]
